/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const SimilarityResult = IDL.Record({
  'startTime' : Time,
  'keyEvents' : IDL.Vec(IDL.Text),
  'endTime' : Time,
  'returnPct30d' : IDL.Float64,
  'returnPct90d' : IDL.Float64,
  'similarityScore' : IDL.Float64,
  'periodLabel' : IDL.Text,
});
export const EventType = IDL.Variant({
  'Geopolitico' : IDL.Null,
  'Macro' : IDL.Null,
  'Estrutural' : IDL.Null,
});
export const HistoricalEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'importance' : IDL.Float64,
  'description' : IDL.Text,
  'predictability' : IDL.Float64,
  'timestamp' : Time,
  'eventType' : EventType,
});
export const FutureEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'importance' : IDL.Float64,
  'description' : IDL.Text,
  'predictability' : IDL.Float64,
  'expectedTime' : Time,
  'eventType' : EventType,
});
export const Direction = IDL.Variant({ 'Alta' : IDL.Null, 'Queda' : IDL.Null });
export const MajorMove = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'returnPct' : IDL.Float64,
  'direction' : Direction,
  'endTime' : Time,
  'relatedEvents' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'analyzeCurrentContext' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(SimilarityResult)],
      ['query'],
    ),
  'getEventsWindow' : IDL.Func(
      [Time, Time],
      [IDL.Vec(HistoricalEvent)],
      ['query'],
    ),
  'getFutureEvents' : IDL.Func([], [IDL.Vec(FutureEvent)], ['query']),
  'getMajorMovesWithEvents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(MajorMove, IDL.Vec(HistoricalEvent)))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const SimilarityResult = IDL.Record({
    'startTime' : Time,
    'keyEvents' : IDL.Vec(IDL.Text),
    'endTime' : Time,
    'returnPct30d' : IDL.Float64,
    'returnPct90d' : IDL.Float64,
    'similarityScore' : IDL.Float64,
    'periodLabel' : IDL.Text,
  });
  const EventType = IDL.Variant({
    'Geopolitico' : IDL.Null,
    'Macro' : IDL.Null,
    'Estrutural' : IDL.Null,
  });
  const HistoricalEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'importance' : IDL.Float64,
    'description' : IDL.Text,
    'predictability' : IDL.Float64,
    'timestamp' : Time,
    'eventType' : EventType,
  });
  const FutureEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'importance' : IDL.Float64,
    'description' : IDL.Text,
    'predictability' : IDL.Float64,
    'expectedTime' : Time,
    'eventType' : EventType,
  });
  const Direction = IDL.Variant({ 'Alta' : IDL.Null, 'Queda' : IDL.Null });
  const MajorMove = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'returnPct' : IDL.Float64,
    'direction' : Direction,
    'endTime' : Time,
    'relatedEvents' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'analyzeCurrentContext' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(SimilarityResult)],
        ['query'],
      ),
    'getEventsWindow' : IDL.Func(
        [Time, Time],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
    'getFutureEvents' : IDL.Func([], [IDL.Vec(FutureEvent)], ['query']),
    'getMajorMovesWithEvents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(MajorMove, IDL.Vec(HistoricalEvent)))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };