/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Direction = { 'Alta' : null } |
  { 'Queda' : null };
export type EventType = { 'Geopolitico' : null } |
  { 'Macro' : null } |
  { 'Estrutural' : null };
export interface FutureEvent {
  'id' : bigint,
  'title' : string,
  'importance' : number,
  'description' : string,
  'predictability' : number,
  'expectedTime' : Time,
  'eventType' : EventType,
}
export interface HistoricalEvent {
  'id' : bigint,
  'title' : string,
  'source' : string,
  'importance' : number,
  'description' : string,
  'predictability' : number,
  'timestamp' : Time,
  'eventType' : EventType,
}
export interface MajorMove {
  'id' : bigint,
  'startTime' : Time,
  'returnPct' : number,
  'direction' : Direction,
  'endTime' : Time,
  'relatedEvents' : Array<bigint>,
}
export interface SimilarityResult {
  'startTime' : Time,
  'keyEvents' : Array<string>,
  'endTime' : Time,
  'returnPct30d' : number,
  'returnPct90d' : number,
  'similarityScore' : number,
  'periodLabel' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'analyzeCurrentContext' : ActorMethod<
    [number, number],
    Array<SimilarityResult>
  >,
  'getEventsWindow' : ActorMethod<[Time, Time], Array<HistoricalEvent>>,
  'getFutureEvents' : ActorMethod<[], Array<FutureEvent>>,
  'getMajorMovesWithEvents' : ActorMethod<
    [],
    Array<[MajorMove, Array<HistoricalEvent>]>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];