/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HistoricalEvent {
    id: bigint;
    title: string;
    source: string;
    importance: number;
    description: string;
    predictability: number;
    timestamp: Time;
    eventType: EventType;
}
export interface MajorMove {
    id: bigint;
    startTime: Time;
    returnPct: number;
    direction: Direction;
    endTime: Time;
    relatedEvents: Array<bigint>;
}
export interface FutureEvent {
    id: bigint;
    title: string;
    importance: number;
    description: string;
    predictability: number;
    expectedTime: Time;
    eventType: EventType;
}
export type Time = bigint;
export interface SimilarityResult {
    startTime: Time;
    keyEvents: Array<string>;
    endTime: Time;
    returnPct30d: number;
    returnPct90d: number;
    similarityScore: number;
    periodLabel: string;
}
export enum Direction {
    Alta = "Alta",
    Queda = "Queda"
}
export enum EventType {
    Geopolitico = "Geopolitico",
    Macro = "Macro",
    Estrutural = "Estrutural"
}
export interface backendInterface {
    analyzeCurrentContext(currentPrice: number, recentReturnPct: number): Promise<Array<SimilarityResult>>;
    getEventsWindow(start: Time, end: Time): Promise<Array<HistoricalEvent>>;
    getFutureEvents(): Promise<Array<FutureEvent>>;
    getMajorMovesWithEvents(): Promise<Array<[MajorMove, Array<HistoricalEvent>]>>;
}
import type { Direction as _Direction, EventType as _EventType, FutureEvent as _FutureEvent, HistoricalEvent as _HistoricalEvent, MajorMove as _MajorMove, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeCurrentContext(arg0: number, arg1: number): Promise<Array<SimilarityResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeCurrentContext(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeCurrentContext(arg0, arg1);
            return result;
        }
    }
    async getEventsWindow(arg0: Time, arg1: Time): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsWindow(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsWindow(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFutureEvents(): Promise<Array<FutureEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFutureEvents();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFutureEvents();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMajorMovesWithEvents(): Promise<Array<[MajorMove, Array<HistoricalEvent>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMajorMovesWithEvents();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMajorMovesWithEvents();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Direction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FutureEvent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FutureEvent): FutureEvent {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_HistoricalEvent_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoricalEvent): HistoricalEvent {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MajorMove_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MajorMove): MajorMove {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    returnPct: number;
    direction: _Direction;
    endTime: _Time;
    relatedEvents: Array<bigint>;
}): {
    id: bigint;
    startTime: Time;
    returnPct: number;
    direction: Direction;
    endTime: Time;
    relatedEvents: Array<bigint>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        returnPct: value.returnPct,
        direction: from_candid_Direction_n13(_uploadFile, _downloadFile, value.direction),
        endTime: value.endTime,
        relatedEvents: value.relatedEvents
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    source: string;
    importance: number;
    description: string;
    predictability: number;
    timestamp: _Time;
    eventType: _EventType;
}): {
    id: bigint;
    title: string;
    source: string;
    importance: number;
    description: string;
    predictability: number;
    timestamp: Time;
    eventType: EventType;
} {
    return {
        id: value.id,
        title: value.title,
        source: value.source,
        importance: value.importance,
        description: value.description,
        predictability: value.predictability,
        timestamp: value.timestamp,
        eventType: from_candid_EventType_n4(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    importance: number;
    description: string;
    predictability: number;
    expectedTime: _Time;
    eventType: _EventType;
}): {
    id: bigint;
    title: string;
    importance: number;
    description: string;
    predictability: number;
    expectedTime: Time;
    eventType: EventType;
} {
    return {
        id: value.id,
        title: value.title,
        importance: value.importance,
        description: value.description,
        predictability: value.predictability,
        expectedTime: value.expectedTime,
        eventType: from_candid_EventType_n4(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_MajorMove, Array<_HistoricalEvent>]): [MajorMove, Array<HistoricalEvent>] {
    return [
        from_candid_MajorMove_n11(_uploadFile, _downloadFile, value[0]),
        from_candid_vec_n1(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Alta: null;
} | {
    Queda: null;
}): Direction {
    return "Alta" in value ? Direction.Alta : "Queda" in value ? Direction.Queda : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Geopolitico: null;
} | {
    Macro: null;
} | {
    Estrutural: null;
}): EventType {
    return "Geopolitico" in value ? EventType.Geopolitico : "Macro" in value ? EventType.Macro : "Estrutural" in value ? EventType.Estrutural : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HistoricalEvent>): Array<HistoricalEvent> {
    return value.map((x)=>from_candid_HistoricalEvent_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FutureEvent>): Array<FutureEvent> {
    return value.map((x)=>from_candid_FutureEvent_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_MajorMove, Array<_HistoricalEvent>]>): Array<[MajorMove, Array<HistoricalEvent>]> {
    return value.map((x)=>from_candid_tuple_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
